name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * *  # monthly lint
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run prek
        uses: j178/prek-action@v3.0.0
